name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm init -y
          npm install --save-dev postcss autoprefixer cssnano terser

      - name: Build and optimize
        run: |
          # Create build directory
          mkdir -p build
          
          # Copy all files from docs to build
          cp -r docs/* build/
          
          # Optimize CSS (if postcss is available)
          if command -v npx &> /dev/null; then
            echo "Optimizing CSS..."
            npx postcss build/css/style.css --use autoprefixer --use cssnano --output build/css/style.css || true
          fi
          
          # Optimize JS (if terser is available)
          if command -v npx &> /dev/null; then
            echo "Optimizing JavaScript..."
            npx terser build/js/script.js --compress --mangle --output build/js/script.js || true
          fi
          
          # Ensure all files are present
          ls -la build/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
